### ISSUE TITLE
Introduce Dependency Injection

### ISSUE THREAD

**Issue by mgolokhov** [mgolokhov/dodroid#112]
Probably, based on Dagger 2

**Comment by JubrilEdu** [comment]
I'd start working on this @mgolokhov

**Comment by mgolokhov** [comment]
Cool!

**Comment by JubrilEdu** [comment]
So, I just checked the codebase and I think we have to move to MVVM first before this task can be achievable. Currently, it seems tightly coupled.
What do you think? @mgolokhov

**Comment by qps-ua-mgolokhov** [comment]
@djubreel Retrofit, GoogleAnalytics, Crashlytics, Sound utility can utilize DI right away.

**Comment by mgolokhov** [comment]
@djubreel Retrofit, GoogleAnalytics, Crashlytics, Sound utility can utilize DI right away.

**Comment by JubrilEdu** [comment]
If that's the case can the issue be splitted? one for the dependencies you mentioned and maybe have the DI based on modules.

**Comment by JubrilEdu** [comment]
@mgolokhov  Can you have a look at this? https://github.com/mgolokhov/dodroid/compare/master...djubreel:feature/DI?expand=1#diff-dbde4834a54fcb38f64a1d0091e36c24

it's a base implementation of DI in the project.

**Comment by mgolokhov** [comment]
@djubreel sorry for the late response, I was sick for more than a week.
Thank you, it's a good start.
Couple observations:
Injecting from a base class Dagger 2 will only satisfy the base class's dependencies, not its subclasses.
Current consumers for Tracker class are BaseApp and InterrogatorFragment
The release build will crash.

I'm working on PR with MVVM, room, coroutines and dagger2 first version here https://github.com/mgolokhov/dodroid/pull/122

**Comment by JubrilEdu** [comment]
Hey @mgolokhov, I hope you are better now? I'd discontinue work on this and go through your branch that contains the changes.

**Comment by mgolokhov** [comment]
resolved in https://github.com/mgolokhov/dodroid/pull/122
