### ISSUE TITLE
Floating Action Button Disppears when list of topic is scrolled.

### ISSUE THREAD

**Issue by JubrilEdu** [mgolokhov/dodroid#117]
How to Reproduce:
- Launch the app and navigate to the list of topics
- Scroll down the list, the floating button disappears.

**Comment by JubrilEdu** [comment]
I investigated and discovered the onNestedScroll method was overridden in the ScrollAwareFABBehavior class. Removing the body actually solves the issue.
@mgolokhov Was the initial intention/idea for doing this (overriding the method)?

**Comment by mgolokhov** [comment]
@djubreel thank you for the report.
Expected behavior you can verify in [Google Play version](https://play.google.com/store/apps/details?id=doit.study.droid)
or to see in gif on the main page (README.md)
By scrolling down the button should hide, by scrolling up it should appear back.

**Comment by JubrilEdu** [comment]
Okay, I'd close this issue this.

**Comment by mgolokhov** [comment]
@djubreel but the current behavior for master branch ([sha](https://github.com/mgolokhov/dodroid/commit/7efb9fc9099d2ca89c2b87205567d838ab10e3a7)) is broken - by scrolling up the button does not reappear (at least for android 9 and 6)

**Comment by mgolokhov** [comment]
@djubreel possible solution is discussed here
https://stackoverflow.com/questions/41761736/android-design-library-25-1-0-causes-floatingactionbutton-behavior-to-stop-worki

**Comment by JubrilEdu** [comment]
I'm working on this now.
