### ISSUE TITLE
Add tags for questions

### ISSUE THREAD

**Issue by mgolokhov** [mgolokhov/dodroid#12]
Add tags, so the user can filter questions.

I like mind maps in the lecture slides, so thinking about to use one as tag explorer, with clickable nodes.

**Comment by JaeW** [comment]
Yes, I like the mind maps, but they are really hard for beginners - very overwhelming if they don't know where to start.  Could there be an alternative representation for newbies?  Something a little more linear?

**Comment by mgolokhov** [comment]
First step would be to implement the list\table of checkbox tags
May be like this 
![elistcbox2](https://cloud.githubusercontent.com/assets/294512/10992236/47b05a22-8475-11e5-8fa6-84d66b0607c6.png)

**Comment by JaeW** [comment]
I'm not sure exactly what I'm looking at.  Sorry . . . .

**Comment by mgolokhov** [comment]
Don't care about data, just structure.
Grey can be level0 - expendable list of tags (activity, intent).
Blue - level1 also with the list of labels.
User can check a whole level or the certain tags.

**Comment by JaeW** [comment]
Yes, that's perfect.

**Comment by mgolokhov** [comment]
connected to https://github.com/mgolokhov/dodroid/issues/31

**Comment by shiraeeshi** [comment]
What needs to be done at this stage to close this issue? There are tags in the app, but they don't form hierarchy. We can add new column "parentTagId" to "tags" table.

**Comment by mgolokhov** [comment]
A good example https://play.google.com/store/apps/details?id=english.grammar.test.app
The easiest way to break it by test sets, so it would be like
<img src="https://cloud.githubusercontent.com/assets/294512/11927550/5fe294f2-a7de-11e5-820b-eb101dab4180.jpg" height="200" width="200">
So this one is connected to the compound key and [expandable topic list](https://github.com/mgolokhov/dodroid/issues/31)

**Comment by shiraeeshi** [comment]
IMHO this isn't intuitive: no one would expect tag to have something inside. If it was a category, then it would be OK for it to have children. Test sets don't fit the model either way: they are neither tags nor categories.
There's no any importance for user to know that some question is from one set and the second is from another. We already form sets by picking questions randomly.
What do you think?

**Comment by mgolokhov** [comment]
It depends =)
My first intent was to build liner, predetermined test sequence, so a user can review all tests.
We should have both modes random and predefined set.
Did you try the english test app? What is your impression?

**Comment by shiraeeshi** [comment]
> Did you try the english test app?

I can't try it at the moment because of a dead battery.

> We should have both modes random and predefined set.

One important difference: in random mode the user can select multiple tags, in predefined-set-mode user can select just one set.
Maybe we should add a new activity for predefined set selection?

**Comment by mgolokhov** [comment]
<img src=https://cloud.githubusercontent.com/assets/294512/12004269/344f86b6-ab5c-11e5-9c66-ea938eab1fc7.png width=200 height=300><img src=https://cloud.githubusercontent.com/assets/294512/12004270/37b69a6a-ab5c-11e5-9a63-af5f35dce01e.png width=200 height=300>

We can have an activity with two tabs.

**Comment by mgolokhov** [comment]
@shiraeeshi is right - tags are implemented. Now we are talking about a new task #31
