### ISSUE TITLE
Incorrect Question - Answer Support

### ISSUE THREAD

**Issue by JaeW** [mgolokhov/dodroid#14]
If user answers question wrong, what feedback should they get?  A hint?  A link to the right Android Developer documentation?  Other?

**Comment by mgolokhov** [comment]
Always should be visible a hint button that loads some explanation and relative links.
Button can light up\blink when the user answers wrongly.

**Comment by JaeW** [comment]
Sorry if I sound like a neuro-freak, but be careful of the blinking - that (for real) could trigger an epileptic seizure.  I think it depends on the rate, though.

**Comment by JaeW** [comment]
Crap.  I'm starting to sound like a real stick-in-the-mud (kill-joy).

**Comment by mgolokhov** [comment]
We can play with this feature. Hard to say before try

**Comment by JaeW** [comment]
My bad.  I'm over-thinking this.

**Comment by mgolokhov** [comment]
After 2 wrong answers let's show the icon (without blinking)
![download](https://cloud.githubusercontent.com/assets/294512/11208751/f469e27c-8d2d-11e5-9e71-8cb5f9e74ec0.png)

By pushing it the user will get a hit (if any) and a link to the external resource (developer.android.com, stackoverflow and etc)

**Comment by mgolokhov** [comment]
Added info icon
<img src=https://cloud.githubusercontent.com/assets/294512/11607901/0fee7734-9b6a-11e5-920c-a9ece8aafdeb.png width=250 height=400>

**Comment by JaeW** [comment]
Like

**Comment by shiraeeshi** [comment]
What needs to be done at this stage to close this issue?

**Comment by mgolokhov** [comment]
Add indication that there is a link to the documentation (if any).

**Comment by mgolokhov** [comment]
Let's show animated bulb after two wrong answers and change a "commit" button to a "next" button mode.

**Comment by mgolokhov** [comment]
After two wrong answers shows a snackbar

<img src=https://cloud.githubusercontent.com/assets/294512/13063177/656ff79e-d456-11e5-9ca8-72ef79ca94ac.png width=150 height=250 img>
