### ISSUE TITLE
Parse.com

### ISSUE THREAD

**Issue by JayBrizle** [mgolokhov/dodroid#19]
If you want to integrate a backend into the application Parse.com is free to setup. I did a tutorial app using them and it's free until your app starts getting any sort of real traffic (more than 30 request per second). Push notifications, database storage, analytics and everything. They were bought by Facebook but still have the same free plans I used before http://parse.com/plans Just a thought for when you reach that point with the app, read over the information. The Android/Java sdk is very straightforward to work with, no SQL queries or anything for the database stuff, just Java code

**Comment by mgolokhov** [comment]
Interesting. We can play with it a bit later.

**Comment by mgolokhov** [comment]
=(
http://blog.parse.com/announcements/moving-on/
