### ISSUE TITLE
Add more questions

### ISSUE THREAD

**Issue by mgolokhov** [mgolokhov/dodroid#2]

**Comment by JayBrizle** [comment]
I'm gathering up more questions to add to the test.json. You just want things from the current course we're taking or anything in general? I am also taking parts 2 and 3 of the course right now and can add things from that as well if you want.

**Comment by mgolokhov** [comment]
It would be nice.
I also enrolled in these parts, but there are tons of information and I concentrated on the first one.
I guess we should define tags for questions, so we can filter by courses/weeks and so on.

**Comment by JayBrizle** [comment]
Ok I'll gather up questions I think are relevant from those courses too. Tags of some sort is a good idea.

**Comment by JaeW** [comment]
If you take the question tags directly from the Course's Weekly Titles the questions will remain relevant even if the course changes structure at some point in the future.  For instance:  "Week 3:  Intents, Permissions and Fragment Class" you would have three tags:  1) Intents, 2) Permissions, 3) Fragment Class.  

But that brings up a potential "problem."  What they teach in Part 1 is fairly simple whereas the same subject covered in a later course would be more advanced.  The more questions a user runs into that are far beyond his/her current understanding the more likely he/she will not use the app.  A computer science professor in Boulder has written about this extensively - you want to keep users in a Zone of Proximal Flow.  In other words, challenged beyond what they are 100% comfortable with, but not in so difficult that they quit.  How do we mark questions for difficulty?  By course?  

I may be putting the horse before the cart, but I could see this being a problem down the road.

**Comment by mgolokhov** [comment]
Good point, it's better to label them by topic (not by course and week).
We can add level tag: level0, level1...
Same question would have many tags, so the user can train in different modes.
[Wiki about our data structure.](https://github.com/mgolokhov/dodroid/wiki/Data%20for%20quiz,%20json%20file%20structure)

**Comment by JayBrizle** [comment]
The new questions I've added that I haven't pull requested yet have added the topic to the tag as well. "Intents" for example, along with the course and week that were already there. We will add plenty more things I'm sure to give us options for the user

**Comment by mgolokhov** [comment]
Connected to [Website - User Input Form to Collect Questions](https://github.com/mgolokhov/dodroid/issues/15)
