### ISSUE TITLE
Screenshots & videos

### ISSUE THREAD

**Issue by mgolokhov** [mgolokhov/dodroid#27]
<img src="https://cloud.githubusercontent.com/assets/294512/11451839/b11c0724-95e4-11e5-91d9-c7e700548a30.png" width="64" height="64"><img src="https://cloud.githubusercontent.com/assets/294512/11451841/b4f0a0f8-95e4-11e5-94c1-437a5a74dc08.png" width="102" height="50">
<img src="https://cloud.githubusercontent.com/assets/294512/10896541/c3bf2ffa-81cb-11e5-8f20-55e5ab30b7f6.png" width="140" height="250"><img src="https://cloud.githubusercontent.com/assets/294512/10896554/cdd746e4-81cb-11e5-8c12-e0f03c6f140e.png" width="140" height="250"><img src="https://cloud.githubusercontent.com/assets/294512/10896560/d56eb55e-81cb-11e5-962d-13768a4e89cc.png" width="140" height="250">

**Comment by mgolokhov** [comment]
<img src="https://cloud.githubusercontent.com/assets/294512/10896500/8956ef2e-81cb-11e5-9a12-36e085281bcc.png" width="150" height="250"><img src="https://cloud.githubusercontent.com/assets/294512/11451834/961c08e8-95e4-11e5-9687-906c2e5c322d.png" width="150" height="250"><img src="https://cloud.githubusercontent.com/assets/294512/11451836/99e78420-95e4-11e5-9582-7872ab7d266e.png" width="150" height="250"><img src="https://cloud.githubusercontent.com/assets/294512/11451837/9d17a9ae-95e4-11e5-81b8-384114967123.png" width="150" height="250">

**Comment by JaeW** [comment]
Maxim, this looks fantastic!

**Comment by mgolokhov** [comment]
<img src="https://cloud.githubusercontent.com/assets/294512/11693503/41d9c9c0-9eb6-11e5-86f4-67063c164196.png" width="230" height="350">

**Comment by JaeW** [comment]
Starting to look _seriously_ professional.  Nice work!  

Trying to hammer out Notifications assignment but am looking forward to taking the new code for a spin.

**Comment by mgolokhov** [comment]
<img src="https://cloud.githubusercontent.com/assets/294512/11976090/d8f35838-a985-11e5-92b3-9a4d26a63f58.png" width="150" height="250"><img src="https://cloud.githubusercontent.com/assets/294512/11976093/dd64fb10-a985-11e5-9a48-53cf4071bd9c.png" width="150" height="250"><img src="https://cloud.githubusercontent.com/assets/294512/11976094/dfea3ab2-a985-11e5-90e9-9d97b18940bf.png" width="150" height="250"><img src="https://cloud.githubusercontent.com/assets/294512/11976095/e1a6ce7e-a985-11e5-96a6-e0e4908b9c11.png" width="150" height="250">

**Comment by mgolokhov** [comment]
<img src=https://cloud.githubusercontent.com/assets/294512/13063178/6573cc34-d456-11e5-8078-c968bd68fd58.png width=150 height=250 img><img src=https://cloud.githubusercontent.com/assets/294512/13063175/656fb50e-d456-11e5-9df8-2e2c8fbdcfc4.png width=150 height=250 img><img src=https://cloud.githubusercontent.com/assets/294512/13063177/656ff79e-d456-11e5-9ca8-72ef79ca94ac.png width=150 height=250 img><img src=https://cloud.githubusercontent.com/assets/294512/13063176/656fd2c8-d456-11e5-9d8f-491a4c7004df.png width=150 height=250 img>

**Comment by mgolokhov** [comment]
<img src=https://cloud.githubusercontent.com/assets/294512/13585805/ef387f9a-e4ce-11e5-94c2-6633986a59a0.png width=150 height=250 img><img src=https://cloud.githubusercontent.com/assets/294512/13585806/f185f35e-e4ce-11e5-8589-b88318c38445.png width=150 height=250 img><img src=https://cloud.githubusercontent.com/assets/294512/13585809/f519de9a-e4ce-11e5-9408-5258c9277b4e.png width=150 height=250 img><img src=https://cloud.githubusercontent.com/assets/294512/13585813/f75655d0-e4ce-11e5-9273-c2cb6c434651.png width=150 height=250 img><img src=https://cloud.githubusercontent.com/assets/294512/13585819/f9fffd72-e4ce-11e5-8bd1-b46f96c7718a.png width=150 height=250 img><img src=https://cloud.githubusercontent.com/assets/294512/13585845/0ba94f60-e4cf-11e5-905c-17663c84a423.png width=150 height=250 img><img src=https://cloud.githubusercontent.com/assets/294512/13585862/26f601be-e4cf-11e5-8630-e67bc890003b.png width=150 height=250 img><img src=https://cloud.githubusercontent.com/assets/294512/13585866/2a4e98d0-e4cf-11e5-9345-365987217dd0.png width=150 height=250 img>

**Comment by mgolokhov** [comment]
<img src=https://cloud.githubusercontent.com/assets/294512/14067302/c46357a8-f46a-11e5-9b27-f242d1bb06ab.png width=150 /><img src=https://cloud.githubusercontent.com/assets/294512/14067303/c7bf6d88-f46a-11e5-85a9-7b6b475221e6.png width=150 /><img src=https://cloud.githubusercontent.com/assets/294512/14067333/b51fc92e-f46b-11e5-91c2-47cd08524a9c.png width=150 /><img src=https://cloud.githubusercontent.com/assets/294512/14067304/ccbb05cc-f46a-11e5-8ae3-feff36fc23f3.png width=150 /><img src=https://cloud.githubusercontent.com/assets/294512/14067305/d1803334-f46a-11e5-809e-9b37cd9f66e6.png width=150 /><img src=https://cloud.githubusercontent.com/assets/294512/14067306/d4f0afa8-f46a-11e5-8381-1f4dda2e770c.png width=150 /><img src=https://cloud.githubusercontent.com/assets/294512/14067308/dcc129d8-f46a-11e5-8123-4d7ee59d6f8e.png width=150 /><img src=https://cloud.githubusercontent.com/assets/294512/14067309/dea55a80-f46a-11e5-9163-848230d938f6.png width=150 />

**Comment by mgolokhov** [comment]
Small screen test

<img src=https://cloud.githubusercontent.com/assets/294512/14231960/22d3abd8-f99f-11e5-8118-62bd785df6f1.gif width=300/>

**Comment by mgolokhov** [comment]
<img src=https://cloud.githubusercontent.com/assets/294512/14364811/38525474-fd13-11e5-9922-1c3e4bef2f2a.gif width=300 />

**Comment by mgolokhov** [comment]
Question in the recyclerview
<img src=https://cloud.githubusercontent.com/assets/294512/15452519/4638454e-1ffa-11e6-86fe-96db193a944d.png width=300 />

**Comment by mgolokhov** [comment]
<img src=https://cloud.githubusercontent.com/assets/294512/15977883/a5752c52-2f63-11e6-9c4e-d7b93a819724.gif width=300/>

**Comment by mgolokhov** [comment]
![untitled2](https://cloud.githubusercontent.com/assets/294512/16547582/f0dcec82-417b-11e6-9bec-78d5c87ecbcb.gif)
