### ISSUE TITLE
Big numbers and small screen can mess layout

### ISSUE THREAD

**Issue by mgolokhov** [mgolokhov/dodroid#28]
![screen shot 2015-12-04 at 00 54 25](https://cloud.githubusercontent.com/assets/294512/11575391/ca1c1084-9a21-11e5-89cc-4b9b99367eaa.png)

**Comment by JaeW** [comment]
I think the right/wrong answer tallies might need more delineation.  Again the <a href="http://www.color-blindness.com/deuteranopia-red-green-color-blindness/">red/green deficiency</a> thing in addition to the fact that, visually, the two scores run together.

**Comment by mgolokhov** [comment]
I see, but this is the compact way to represent data. We can add a tooltip. Also a user can define counters indirectly by Toast message and which one is incremented.

**Comment by JaeW** [comment]
I also propose that we replace the quote, "a journey of a thousand miles begins with a single step," with the quote, "that which does not kill us makes us stronger."  
![image](https://cloud.githubusercontent.com/assets/10471736/11619594/753aecc0-9c6f-11e5-9f20-1faed3f07380.png)

**Comment by JaeW** [comment]
BTW, remember that red/green color deficiency/blindness that is found in about 7% of the population?  The green on the correct score is almost invisible on my phone (an HTC One M8) but not on my pc . . . . maybe change the shade to include a higher percentage of blue?   Or maybe this is another one of those setting options?  I think #388E3C would work.

**Comment by mgolokhov** [comment]
> I also propose that we replace the quote, "a journey of a thousand miles begins with a single step," with the quote, "that which does not kill us makes us stronger."

We can update quotes automatically from time to time =)

> #388E3C

the color for header?

**Comment by JaeW** [comment]
No need to update quote.  I was just being a smartass.  ;-)

Sorry, I wasn't precise in my description.  For the scores you have the number of correct answers in green and number of incorrect answers in red.  I was referring to the color of the correct number of answers.  Had I not already seen the screenshot  (where, oddly, I can see the green) before looking at the app on my phone, I would not have even known that the number of correct answers was being displayed.  If you include a green with more blue (#388E3C) it will still appear green, but will actually be visible to oddballs like me.  

What's weird is that I know the color you used is the defined system color GREEN, so it makes me wonder how many components of other apps I (and other colorblind people) are not seeing.
