### ISSUE TITLE
Add dividers and spaces between items in RecyclerView

### ISSUE THREAD

**Issue by mgolokhov** [mgolokhov/dodroid#29]
http://stackoverflow.com/questions/24618829/how-to-add-dividers-and-spaces-between-items-in-recyclerview

**Comment by JaeW** [comment]
So you're wanting dividers between the question area and the area which holds the score, commit button and question count?  Also between the question and the tag display at the top underneath the App Bar?

**Comment by mgolokhov** [comment]
I pushed a new activity with the topic chooser (a stub for now).
It's implemented with the help of RecyclerView.
By default, RecyclerView doesn't have dividers like ListView.

**Comment by JaeW** [comment]
Yes, saw that issue in the link.  Just wasn't sure I understood the problem correctly.
