### ISSUE TITLE
Add text that shows when the answer is right or wrong

### ISSUE THREAD

**Issue by JayBrizle** [mgolokhov/dodroid#3]
As an enhancement maybe add a simple text animation that displays above the question confirming the answer is right or wrong to go along with the background color of the navigation turning green and red.

**Comment by mgolokhov** [comment]
We can play with different layouts and than make opinion poll

**Comment by mgolokhov** [comment]
Added toast message. We can also add a list of exclamations: awesome, excellent, impressive... and change them periodically (with sound even better).

![screen shot 2015-11-05 at 23 03 46](https://cloud.githubusercontent.com/assets/294512/10980159/91966604-8411-11e5-8f84-f474203307d4.png)

**Comment by JaeW** [comment]
Visual cues beside color are super important.  Almost 10% of men (rare in women) have some form of red/green color "blindness."  For some it depends on shade/intensity - other can't see these colors at all.
