### ISSUE TITLE
Right Counter Allows Same Question to Increment Multiple Times

### ISSUE THREAD

**Issue by JaeW** [mgolokhov/dodroid#30]
You can answer the same question repeatedly - each time it will increment the score.

**Comment by mgolokhov** [comment]
Yes, the issue is connected to https://github.com/mgolokhov/dodroid/issues/23
All views are recreated by commit button

**Comment by mgolokhov** [comment]
For submitting a bug use title for short description and you have many labels (bug in our case) on the right sight. 
![screen shot 2015-12-07 at 08 43 28](https://cloud.githubusercontent.com/assets/294512/11619948/9d5677d4-9cbe-11e5-9ddf-b0b74fb0da91.png)

**Comment by JaeW** [comment]
Better?

**Comment by JaeW** [comment]
Ha!  Now perfect.

**Comment by mgolokhov** [comment]
You can increment wrong counter many times, but the right answer should disable commit button

**Comment by JaeW** [comment]
Would it be possible, instead, to advance the user to the next question if they answer correctly?  Seems simpler and more user-friendly.

**Comment by mgolokhov** [comment]
Sure, all is possible, but sometimes you can guess the right answer. And in this case a user may want to stay a bit (print on the memory). 
We can do it in settings.

**Comment by JaeW** [comment]
Like the settings option.  I think the visualization of the question automatically sliding to the next one gives the brain the impression of moving forward. . . . . in other words, progressing.  Gives a tiny dopamine release (really, really).

**Comment by JaeW** [comment]
BTW, the RecyclerView has built-in animation, so I believe the slide effect is built-in.  Found this about <a href=https://developer.android.com/reference/android/support/v7/widget/RecyclerView.ItemAnimator.html">RecyclerView.ItemAnimator</a>.   Hopefully helpful.

**Comment by JaeW** [comment]
This <a href=https://github.com/gabrielemariotti/RecyclerViewItemAnimators">Item Animation Library</a> is pretty sweet.

**Comment by mgolokhov** [comment]
I'm pretty sure it's hard to slide all page, seems item animation is used just for items.
Even in the Big Nerd Ranch Android book they use ViewPager.
My guess, it can be done by implementing custom LayoutManager with lots of code.

**Comment by JaeW** [comment]
You know what?  It's nowhere near essential at this point anyway -- way more important things that need to be done.  But I'll do some looking around.  If I find a true positive I'll post.  If not, forget.  :-)

**Comment by mgolokhov** [comment]
Anyway, RecyclerView beats ListView and animation is a killer feature.

**Comment by mgolokhov** [comment]
Mmm, [a ViewPager implementation based on RecyclerView's code](https://github.com/lsjwzh/RecyclerViewPager).

**Comment by JaeW** [comment]
Definitely agree.  Am reading <a href="http://www.amazon.com/Android-User-Interface-Design-Implementing-ebook/dp/B018BI07P0/ref=mt_kindle?_encoding=UTF8&me=">this book</a> on material design for programmers (not designers).  Google has included some really slick stuff with the new Material Design features.  Going to work on those GitHub classes now . . . .

**Comment by JaeW** [comment]
Sweet animation library!  Definitely like.
