### ISSUE TITLE
Implement question like and dislike

### ISSUE THREAD

**Issue by mgolokhov** [mgolokhov/dodroid#49]
send statistics through google analitics

**Comment by JaeW** [comment]
Propose that the dislike response be more robust so the feedback is actionable, i.e., why don't you like this question?  
Suggested responses:
- question does not make sense
- answer to question is incorrect
- the reference link is broken or not relevant

**Comment by mgolokhov** [comment]
Yep =)
Report because:
- question incorrect
- answer incorrect
- documentation irrelevant

And EditText widget with hit "Your comment here" and commit button (FAB)

**Comment by JaeW** [comment]
Yes, yes.  Definitely like.

**Comment by mgolokhov** [comment]
<img src=https://cloud.githubusercontent.com/assets/294512/14044622/ae40a2d2-f2a3-11e5-97b9-f89043f512d9.png width=200/>

**Comment by mgolokhov** [comment]
In google analytics it looks like 

![screen shot 2016-03-28 at 13 59 11](https://cloud.githubusercontent.com/assets/294512/14076771/8774f95e-f4ed-11e5-973f-08c8c43c68e3.png)
