### ISSUE TITLE
Add FAB in the Topic Activity

### ISSUE THREAD

**Issue by mgolokhov** [mgolokhov/dodroid#63]
To use drawer every time is overkill.

**Comment by JaeW** [comment]
Was going to suggest this very thing.  I like the idea of a FAB - just pick the topic and click the FAB.  Elegant.  Simple.

**Comment by JaeW** [comment]
Currently, in the navigation drawer menu, you're using a custom icon to begin the quiz (ic_lightning_sword.png).  Is this the icon you want to use on the FAB, or do you want to go with a more standard icon like <a href="https://materialdesignicons.com/">this</a> or <a href="https://design.google.com/icons/">this</a> as recommended in the Material Design guidelines?

**Comment by mgolokhov** [comment]
For consistency should be the same.

**Comment by JaeW** [comment]
Agree on consistency issue.  So current icon?  or material design icon?  I think a play button (right-pointing arrow) might be more intuitive, but am fine with whichever.  Just wanted to point out material design guidelines.  :)

**Comment by JaeW** [comment]
Added the FAB in my forked version.  For consistency, I made the background color and attributes same as FAB in quiz.  Using ic_lightning_sword.png didn't work on the FAB - it is not visible with the background color.  Temporarily added a Material Design icon.  Added onClickListener, but debating on how to access method createBackStack(intent) in DrawerBaseActivity.  Perhaps create interface which DrawerBaseActivity implements?  Not sure.  Would like to hear your thoughts.

**Comment by mgolokhov** [comment]
First you have to [sync with current state of remote branch](https://help.github.com/articles/syncing-a-fork/).
Next check function https://github.com/mgolokhov/dodroid/blob/fa5258271c60d2aac293e4f121631d0aa5c5ac83/app/src/main/java/doit/study/droid/activities/DrawerBaseActivity.java#L157

**Comment by JaeW** [comment]
So what happens if I have committed changes to my forked repo on GitHub but
don't want to push them to your master?  I didn't branch - oops.  Still
possible to simply pull your changes and abandon mine?

On Fri, Jun 10, 2016 at 1:09 AM, Maxim Golokhov notifications@github.com
wrote:

> First you have to sync with current state of remote branch
> https://help.github.com/articles/syncing-a-fork/.
> Next check function
> https://github.com/mgolokhov/dodroid/blob/fa5258271c60d2aac293e4f121631d0aa5c5ac83/app/src/main/java/doit/study/droid/activities/DrawerBaseActivity.java#L157
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/mgolokhov/dodroid/issues/63#issuecomment-225101384,
> or mute the thread
> https://github.com/notifications/unsubscribe/AJ_JOEN3Uss9aBGdKhRsLhhmH2Lm54VBks5qKP9_gaJpZM4IFquN
> .

## 

Janice Wildrick
314-651-4597

“There is no passion to be found playing small - in settling for a life
that is less than the one you are capable of living.”  -- Nelson Mandela

**Comment by mgolokhov** [comment]
You may try 

```
git checkout master
git branch new-branch-to-save-current-commits
git fetch --all
git reset --hard origin/master
```

[check link](http://stackoverflow.com/questions/1125968/force-git-to-overwrite-local-files-on-pull)

**Comment by JaeW** [comment]
Deleted my fork.  Re-forked.  Lazy solution, but a solution nonetheless.  Will branch before making changes in the future. Thanks.

**Comment by mgolokhov** [comment]
You may just clone in another folder, so not to loose your changes.

**Comment by JaeW** [comment]
Too late.  Already done.  Recreating changes ... good practice.

**Comment by mgolokhov** [comment]
![untitled](https://cloud.githubusercontent.com/assets/294512/16454774/b962a828-3e1a-11e6-9c78-39c9e9943aa4.gif)
