### ISSUE TITLE
Change colour of feedback toast to smth more readable

### ISSUE THREAD

**Issue by mgolokhov** [mgolokhov/dodroid#67]
green is fine
red should be changed

**Comment by JaeW** [comment]
Possible alternative?  What about a hidden image view which displays for a few seconds with either a large green checkmark or large red x in response to question answer?

**Comment by mgolokhov** [comment]
Can be custom toast like 

![screen shot 2016-05-30 at 17 56 29](https://cloud.githubusercontent.com/assets/294512/15652594/ec02ad5c-268f-11e6-90bb-f51ca5cf4aa7.png)

![bemdt](https://cloud.githubusercontent.com/assets/294512/15652597/f06fcc1c-268f-11e6-9d9f-f07e7977d0e7.jpg)

**Comment by JaeW** [comment]
Like the custom error and success toasts - a lot.  Perhaps 3 custom toasts:  1) success, 2) first error, 3) second error which informs user to move to next question.

**Comment by mgolokhov** [comment]
Clickable images:

<img src=https://cloud.githubusercontent.com/assets/294512/16455505/3e7fe01e-3e1d-11e6-96e2-95c3a324fe4f.png width=200><img src=https://cloud.githubusercontent.com/assets/294512/16455516/4625281a-3e1d-11e6-89b5-57329fe4b91f.png width=200>

**Comment by mgolokhov** [comment]
![untitled](https://cloud.githubusercontent.com/assets/294512/16488990/08594aa6-3edc-11e6-9cc3-01ebbb501c3e.gif)
