### ISSUE TITLE
Back Button Behavior

### ISSUE THREAD

**Issue by JaeW** [mgolokhov/dodroid#72]
Back Button Behavior - I would suggest the following:
1. When finished with a quiz, if it doesn’t automatically take the user back to the topic selection activity, the back button should take them there (or the home page if one is implemented)
2. When in the middle of a question, if the back button is pressed it should either take the user back to the previous question or back to the topic selection screen - currently it kicks them out.  
3. In Android’s Gmail app, when the navigation drawer is visible and the back button is pressed, it takes the user back to the activity they were on before they displayed the nav drawer.  I would suggest the same behavior.  

In general, it’s too easy for the user to get kicked out of the app without meaning to exit.

**Comment by mgolokhov** [comment]
A new behavior:
![test_nav](https://cloud.githubusercontent.com/assets/294512/15935494/1cd30f5c-2e70-11e6-97c8-8654f1f9750b.gif)
