### ISSUE TITLE
Add User statistics

### ISSUE THREAD

**Issue by mgolokhov** [mgolokhov/dodroid#8]

**Comment by JaeW** [comment]
Will the app be pushing collected data up to a cloud DB?  Will the user's statistics be comparing him/her to all the other users?  Or will statistics be for the single user?  Will you keep track of percentage success rate per question (to test whether the question is clear & valid)?

**Comment by mgolokhov** [comment]
In the bright future =)
At a minimum we have to store\track progress, so we can reword.
Second step would be to push data up to server (standard alone or coursera).

**Comment by JaeW** [comment]
Oh!  That's a good point.  If we keep all the data on a cloud server who pays?  It's interesting Amazon is trying to attract developers through that whole "get a free ebook" ploy.  I wonder if they would potentially give any AWD services away to new developers.  Just something to think about later.

**Comment by shiraeeshi** [comment]
What needs to be done at this stage to close this issue? Implement a backend?

**Comment by mgolokhov** [comment]
Expand statistic for every question, number of tries, check progress (studied vs unstudied questions) etc.

**Comment by mgolokhov** [comment]
First step- we need a list of events to track.

**Comment by shiraeeshi** [comment]
Do you plan to add new Statistics Activity?

**Comment by mgolokhov** [comment]
Finally it would be an Activity with extended statistics.
For now I think about one good use-case:
A user tried various of tests and some of them he failed. After a while he would like to re-test failed one (review mode).

So we need statistics for every question and pop to the current test set problems with the lowest hits.
